[package]
name = "gesist-bin"
version = "0.1.0"
edition = "2021"

description = "GEminiLab's SImple and STupid b2t encoding"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gesist"
path = "src/main.rs"

[dependencies]
base64 = "0.22.0"
clap = { version = "4.5.3", features = ["derive"] }
gesist = { path = "../.." }
